package propensi.sixacti.model;

public enum ERole {
    ROLE_ADMIN,
    ROLE_PELAMAR,
    ROLE_KARYAWANTETAP,
    ROLE_ASSISTANTMANAGER,
    ROLE_DEPARTMENTMANAGER,
    ROLE_SECTIONMANAGER,
    ROLE_KARYAWANKONTRAK
}